doc/urls.py
from django.conf.urls import url
from . import views


app_name = 'doc'
urlpatterns = [
    url(r'^$', views.index, name = 'index'),

    ### Documents section ###
    # /doc/71/
    url(r'^doc/(?P<doc_id>[0-9]+)/$', views.DocumentDetail, name = 'DocumentDetail'),
    url(r'^doc/$', views.documents, name = 'documents'),
    # add_doc
    # url(r'^doc/add/$', views.DocCreate.as_view(), name = 'doc-add'),
    url(r'^income_form/$', views.incomeCreate.as_view(), name = 'income_form'),
    url(r'^doc_form/$', views.DocCreate.as_view(), name = 'doc-add'),

    ### Clients section ###
    url(r'^client/$', views.clients, name = 'clients'),
    url(r'^client/(?P<cli_id>[0-9]+)/$', views.ClientDetail, name = 'ClientDetail'),

    ### Products section ###

    url(r'^products/$', views.products, name='products'),
    url(r'^products/(?P<product_id>[0-9]+)/$', views.productDetail, name = 'productDetail'),
]

music/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name = 'index'),
    
    # /music/
    url(r'^(?P<album_id>[0-9]+)/$', views.detail, name = 'detail'),
    url(r'^(?P<dokument_id>[0-9]+)/$', views.detail, name = 'detail'),
]

strona/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^music/', include('music.urls')),
    url(r'^doc/', include('doc.urls')),
    url(r'^formsy', include('formsy.urls')),
    
]

doc/models.py
from __future__ import unicode_literals

from django.db import models

from django.db.models import CharField, IntegerField, BooleanField, ForeignKey, FloatField, DateField

from datetime import date

from django.forms import ModelForm

from django.core.urlresolvers import reverse

from django.db.models.signals import pre_save

from django.dispatch import receiver

# Create your models here.

class Client(models.Model):
    code = CharField(max_length=50)
    name = CharField(max_length=100)
    nip = CharField(max_length=10)
    street = CharField(max_length=100)
    number = IntegerField()
    city = CharField(max_length=50)
    zip_number = CharField(max_length=5)

    def get_absolute_url(self):
        return reverse('doc:clidetail', kwargs={ 'cli_id': self.id })

    def __str__(self):
        return "  " + self.code + " " + self.name + " " + self.nip + " " + self.zip_number + " " + self.city + " " + self.street + " " + str(self.number)

class Product(models.Model):
    itswine = BooleanField(default=True)
    name = CharField(max_length=50)
    year = CharField(max_length=4)
    color = CharField(max_length=15)
    dryness = CharField(max_length=20)

    def __str__(self):
        return self.name + " " + self.year + " " + self.color + " " + self.dryness

def getNumber():
    doc = Doc.objects.order_by('number').last().number + 1
    return doc


class Doc(models.Model):

    WZ = 'WZ'
    PZ = 'PZ'
    RW = 'RW'
    PW = 'PW'

    DOC_TYPE_CHOICES=(
        (WZ, 'WZ'),
        (PZ, 'PZ'),
        (RW, 'RW'),
        (PW, 'PW'),
    )

    doctype = models.CharField(
        max_length=2,
        choices=DOC_TYPE_CHOICES,
        default=WZ,
    )

    number = IntegerField()

    date = DateField(default=date.today)

    number=IntegerField(default=getNumber)

    client=ForeignKey(Client, on_delete=models.CASCADE)

    def get_dec_url(self):
        dec = self.id - 1
        return reverse('doc:DocumentDetail', kwargs={'doc_id': dec})

    def get_inc_url(self):
        inc = self.id + 1
        return reverse('doc:DocumentDetail', kwargs={'doc_id': inc})

    def get_absolute_url(self):
        return reverse('doc:DocumentDetail', kwargs={ 'doc_id': self.id })
        # return reverse('doc:detail', kwargs={ 'doc_id': self.id })

    def __str__(self):
        if self.number < 10:
            return self.doctype + " / " + "00" + str(self.number)
        elif self.number < 100:
            return self.doctype + " / " + "0" + str(self.number)
        else:
            return " " + self.doctype + " / " + str(self.number)

class income(models.Model):
    docum = ForeignKey(Doc, on_delete=models.CASCADE)
    product = ForeignKey(Product, on_delete=models.CASCADE)
    quantity = FloatField()
    price = FloatField()
    value = FloatField(null=True, blank=True)

    def __str__(self):
        return str(self.docum) + " operacja nr " + str(self.id)


'''
class expenditure(models.Model):
	number = ForeignKey(Doc, on_delete=models.CASCADE)
	product = ForeignKey(Product, on_delete=models.CASCADE)
	quantity = IntegerField()
	price = FloatField()
	value = FloatField()

'''

doc/forms.py
from django import forms

from django.forms import ModelForm

from doc.models import Doc, Client, income


class Adddoc(ModelForm):
    class Meta:
        model = Doc
        fields = [ 'doctype', 'number', 'date', 'client' ]

class AddCli(ModelForm):
    class Meta:
        model = Client
        fields = [ 'code', 'name', 'nip', 'street', 'number', 'city', 'zip_number' ]

class IncomeForm(ModelForm):
    class Meta:
        model = income
        fields = ['docum', 'product', 'quantity', 'price', 'value']

        def docum_id(doc_id):
            docum = doc_id

doc/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponse, Http404
from .models import Doc, Client, Product, income
from .forms import Adddoc, IncomeForm
from django.views.generic.edit import CreateView, UpdateView, DeleteView


# Create your views here.

all_doc = Doc.objects.order_by('number').all().reverse()
all_clients = Client.objects.order_by('code').all()
all_products = Product.objects.order_by('name').all()


### General section ###

def index(request):
    return render(request, 'doc/index.html', {'all_doc': all_doc, 'all_clients': all_clients})

### Documents section ###

def documents(request):
    return render(request, 'doc/doc/documents.html', { 'all_doc': all_doc })

def all_inc_func(doc_id):
    all_inc = income.objects.filter(docum_id=doc_id)

    return {'all_inc': all_inc}


def doc_calculation(doc_id):

    all_inc = income.objects.filter(docum_id=doc_id)

    # quantity sum calculation (var q)
    q = 0

    for i in all_inc:
        q = q + i.quantity

    # valume sum calculation (var v)
    v = 0

    return {'q': q, 'v': v}


def DocumentDetail(request, doc_id):

    try:
        doc = Doc.objects.get(pk=doc_id)
        q = doc_calculation(doc_id).q
        v = doc_calculation(doc_id).v

    except Doc.DoesNotExist:
        raise Http404("Document does not exist")

    return render(request, 'doc/doc/detail.html', {'doc': doc, 'all_inc': all_inc, 'quantity_sum': q, 'valume_sum': v, 'dec': dec, 'inc': inc})

'''
    #if not doc.DoesNotExist:

    else:

        q = doc_calculation(doc_id).q
        v = doc_calculation(doc_id).v

        # calkulation for "poprzedni" and "nastepny" button

        doc_id = int(doc_id)

        dec = doc_id - 1

        try:
            dec = Doc.objects.get(pk = dec)
        except Doc.DoesNotExist:
            dec = Doc.objects.order_by('id').first()

        inc = doc_id + 1

        try:
            inc = Doc.objects.get(pk = inc)
        except Doc.DoesNotExist:
            if Doc.objects.order_by('id').last().id == doc_id:
                inc = Doc.objects.order_by('id').last()
            else:
                try:
                    inc = inc + 1
                except inc >= doc_id:
                    pass


'''

class DocCreate(CreateView):
    model = Doc
    fields = ['doctype', 'number', 'date', 'client' ]



    def idreturn(self):
        doc_id = self.id
        return doc_id

class incomeCreate(CreateView):
    model = income
    fields = ['docum', 'product', 'quantity', 'price', 'value']

### Clients section ###


def clients(request):
    return render(request, 'doc/client/clients.html', { 'all_clients': all_clients })

def ClientDetail(request, cli_id):
    try:
        client = Client.objects.get(pk=cli_id)
    except Client.DoesNotExist:
        raise Http404("Client does not exist")

    return render(request, 'doc/client/client_detail.html', { 'client': client })

### Products section

def products(request):
    return render(request, 'doc/products/products.html', { 'all_products': all_products })

def productDetail(request, product_id):
    try:
        product = Product.objects.get(pk=product_id)
    except Product.DoesNotExist:
        raise Http404("Product does not exist")

    return render(request, 'doc/products/product_detail.html', { 'product': product })

doc/templates/doc/back-home.html
{% block body %}

{% endblock %}

<br>
<br>
<form action="{% url 'doc:index' %}">
    <input class='back_btn' type="submit" value="POWRÓT">
</form>

doc/templates/doc/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="pl_PL">
<head>

    <meta charset="UTF-8">

    <title> superMAG </title>

    <link href='https://fonts.googleapis.com/css?family=Lato:400,700&subset=latin,latin-ext' rel='stylesheet' type='text/css'>

    <!-- BOOTSTRAP -->

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <!-- jQuery library -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <!-- Latest compiled JavaScript -->
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

    <link rel="stylesheet" type="text/css" href="{% static 'css/doc.css' %}">

</head>
<body>



	<!-- <a class='btn submit' href="{% url 'doc:doc-add' %}" > Add doc </a>
	<a class='btn submit' href="#" > Add cli </a> -->




<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#"> SuperMag </a>
    </div>
    <ul class="nav navbar-nav">
      <li class="active"><a href="{% url 'doc:documents' %}"> DOKUMENTY </a></li>
      <li><a href="{% url 'doc:products' %}"> PRODUKTY </a></li>
      <li><a href="{% url 'doc:clients' %}"> KLIENCI </a></li>
      <li><a href="#"> RAPORTY </a></li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <li><a href="#"><span class="glyphicon glyphicon-log-in"> </span> Zaloguj się </a></li>
    </ul>
  </div>
</nav>

<div class="conmine">
{% block body %}

{% endblock %}
</div>

</body>
</html>

doc/templates/doc/detail.html
{% extends 'doc/base.html' %}

{% block body %}
<div>
	<h3> Numer dokumentu: {{ doc.doctype }} / {{ doc.number }} </h3>
	<br>
	<h3> Data dokumentu: {{ doc.date }} </h3>
	<br>
	<br>
	<h3> <stoong> Klient: </stoong> {{ doc.client }}
</div>
<br>
<br>
<form action="{% url 'doc:index' %}">
	<button class='btn back' type="submit"> POWRÓT </button>
</form>

{% endblock %}

doc/templates/doc/doc_form.html
{% extends 'doc/base.html' %}

{% block body %}
    <div class="topbtns">
        <a href="#" class="btn btn-success topbtn"> POPRZEDNI </a>
        <a href="#" class="btn btn-success topbtn"> NASTĘPNY </a>
    </div>

    <form action="" method="post" enctype="multipart/form-data" >

        {% csrf_token %}
        {% for field in form %}

            {{ field.error }}
            <label> {{ field.label_tag }} </label>
            <div> {{ field }} </div>
            <br>

        {% endfor %}

        <a href="{% url 'doc:documents' %}" class='btn btn-danger'> POWRÓT </a>
        <button class='btn btn-success' type="submit"> POTWIERDŹ </>
    </form>


{% endblock %}

doc/templates/doc/income_form.html
{% extends 'doc/base.html' %}

{% block body %}
    <div class="topbtns">
        <a href="#" class="btn btn-success topbtn"> POPRZEDNI </a>
        <a href="#" class="btn btn-success topbtn"> NASTĘPNY </a>
    </div>

<form action="" method="post" enctype="multipart/form-data" >

    {% csrf_token %}
    {% for field in form %}

        {{ field.error }}
        <label> {{ field.label_tag }} </label>
        <div> {{ field }} </div>
        <br>

    {% endfor %}


	<button class='btn btn-success' type="submit"> POWRÓT </button>
</form>

<script>
    function val() {
        quantity = document.getElementById('id_quantity').value;
        price = document.getElementById('id_price').value;
        document.getElementById('id_value').value = quantity * price;
    };

    document.getElementById('id_quantity').addEventListener("focus", val(), true);
    document.getElementById('id_price').addEventListener("focus", val(), true);
    document.getElementById('id_quantity').addEventListener("blur", val(), true);
    document.getElementById('id_price').addEventListener("blur", val(), true);

</script>

{% endblock %}

doc/templates/doc/index.html
{% extends 'doc/base.html' %}


{% block body %}
<div class = "tab">
	<div id="doc">
		<h1> Lista dokumentów: </h1>

		<ul>
			{% for doc in all_doc %}
				<li><a href="{% url 'doc:detail' doc.id %}"> {{ doc.doctype }} / {{ doc.number }} </a><li>
			{% endfor %}
		</ul>

	</div>
    <div id="cli">
        <h1> Lista klientów </h1>

        <ol>

            {% for client in all_clients %}
                <li> {{ client }} <strong> MIASTO: </strong> {{ client.city }} </li>
            {% endfor %}
    
        </ol>
    </div>
</div>

{% endblock %}