doc/urls.py
from django.conf.urls import url
from . import views


app_name = 'doc'
urlpatterns = [
    url(r'^$', views.index, name = 'index'),

    ### Documents section ###
    # /doc/71/
    url(r'^doc/(?P<doc_id>[0-9]+)/$', views.DocumentDetail, name = 'DocumentDetail'),
    url(r'^doc/$', views.documents, name = 'documents'),
    # add_doc
    # url(r'^doc/add/$', views.DocCreate.as_view(), name = 'doc-add'),
    url(r'^income_form/$', views.incomeCreate.as_view(), name = 'income_form'),
    url(r'^doc_form/$', views.DocCreate.as_view(), name = 'doc-add'),

    ### Clients section ###
    url(r'^client/$', views.clients, name = 'clients'),
    url(r'^client/(?P<cli_id>[0-9]+)/$', views.ClientDetail, name = 'ClientDetail'),

    ### Products section ###

    url(r'^products/$', views.products, name='products'),
    url(r'^products/(?P<product_id>[0-9]+)/$', views.productDetail, name = 'productDetail'),
]

strona/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^music/', include('music.urls')),
    url(r'^doc/', include('doc.urls')),
    url(r'^formsy', include('formsy.urls')),
    
]

doc/models.py
from __future__ import unicode_literals

from django.db import models

from django.db.models import CharField, IntegerField, BooleanField, ForeignKey, FloatField, DateField

from datetime import date

from django.forms import ModelForm

from django.core.urlresolvers import reverse

from django.db.models.signals import pre_save

from django.dispatch import receiver

# Create your models here.

class Client(models.Model):
    code = CharField(max_length=50)
    name = CharField(max_length=100)
    nip = CharField(max_length=10)
    street = CharField(max_length=100)
    number = IntegerField()
    city = CharField(max_length=50)
    zip_number = CharField(max_length=5)

    def get_absolute_url(self):
        return reverse('doc:clidetail', kwargs={ 'cli_id': self.id })

    def __str__(self):
        return "  " + self.code + " " + self.name + " " + self.nip + " " + self.zip_number + " " + self.city + " " + self.street + " " + str(self.number)

class Product(models.Model):
    itswine = BooleanField(default=True)
    name = CharField(max_length=50)
    year = CharField(max_length=4)
    color = CharField(max_length=15)
    dryness = CharField(max_length=20)

    def __str__(self):
        return self.name + " " + self.year + " " + self.color + " " + self.dryness

def getNumber():
    doc = Doc.objects.order_by('number').last().number + 1
    return doc


class Doc(models.Model):

    WZ = 'WZ'
    PZ = 'PZ'
    RW = 'RW'
    PW = 'PW'

    DOC_TYPE_CHOICES=(
        (WZ, 'WZ'),
        (PZ, 'PZ'),
        (RW, 'RW'),
        (PW, 'PW'),
    )

    doctype = models.CharField(
        max_length=2,
        choices=DOC_TYPE_CHOICES,
        default=WZ,
    )

    number = IntegerField()

    date = DateField(default=date.today)

    number=IntegerField(default=getNumber)

    client=ForeignKey(Client, on_delete=models.CASCADE)

    def get_dec_url(self):
        dec = self.id - 1
        return reverse('doc:DocumentDetail', kwargs={'doc_id': dec})

    def get_inc_url(self):
        inc = self.id + 1
        return reverse('doc:DocumentDetail', kwargs={'doc_id': inc})

    def get_absolute_url(self):
        return reverse('doc:DocumentDetail', kwargs={ 'doc_id': self.id })
        # return reverse('doc:detail', kwargs={ 'doc_id': self.id })

    def __str__(self):
        if self.number < 10:
            return self.doctype + " / " + "00" + str(self.number)
        elif self.number < 100:
            return self.doctype + " / " + "0" + str(self.number)
        else:
            return " " + self.doctype + " / " + str(self.number)

class income(models.Model):
    docum = ForeignKey(Doc, on_delete=models.CASCADE)
    product = ForeignKey(Product, on_delete=models.CASCADE)
    quantity = FloatField()
    price = FloatField()
    value = FloatField(null=True, blank=True)

    def __str__(self):
        return str(self.docum) + " operacja nr " + str(self.id)


'''
class expenditure(models.Model):
	number = ForeignKey(Doc, on_delete=models.CASCADE)
	product = ForeignKey(Product, on_delete=models.CASCADE)
	quantity = IntegerField()
	price = FloatField()
	value = FloatField()

'''

doc/forms.py
from django import forms

from django.forms import ModelForm

from doc.models import Doc, Client, income


class Adddoc(ModelForm):
    class Meta:
        model = Doc
        fields = [ 'doctype', 'number', 'date', 'client' ]

class AddCli(ModelForm):
    class Meta:
        model = Client
        fields = [ 'code', 'name', 'nip', 'street', 'number', 'city', 'zip_number' ]

class IncomeForm(ModelForm):
    class Meta:
        model = income
        fields = ['docum', 'product', 'quantity', 'price', 'value']

        def docum_id(doc_id):
            docum = doc_id

doc/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponse, Http404
from .models import Doc, Client, Product, income
from .forms import Adddoc, IncomeForm
from django.views.generic.edit import CreateView, UpdateView, DeleteView


# Create your views here.

all_doc = Doc.objects.order_by('number').all().reverse()
all_clients = Client.objects.order_by('code').all()
all_products = Product.objects.order_by('name').all()


### General section ###

def index(request):
    return render(request, 'doc/index.html', {'all_doc': all_doc, 'all_clients': all_clients})

### Documents section ###

def documents(request):
    return render(request, 'doc/doc/documents.html', { 'all_doc': all_doc })

def all_inc_func(doc_id):
    all_inc = income.objects.filter(docum_id=doc_id)

    return {'all_inc': all_inc}


def doc_calculation(doc_id):

    all_inc = income.objects.filter(docum_id=doc_id)

    # quantity sum calculation (var q)
    q = 0

    for i in all_inc:
        q = q + i.quantity

    # valume sum calculation (var v)
    v = 0

    return {'q': q, 'v': v}


def DocumentDetail(request, doc_id):

    try:
        doc = Doc.objects.get(pk=doc_id)
        q = doc_calculation(doc_id).q
        v = doc_calculation(doc_id).v

    except Doc.DoesNotExist:
        raise Http404("Document does not exist")

    return render(request, 'doc/doc/detail.html', {'doc': doc, 'all_inc': all_inc, 'quantity_sum': q, 'valume_sum': v, 'dec': dec, 'inc': inc})

'''
    #if not doc.DoesNotExist:

    else:

        q = doc_calculation(doc_id).q
        v = doc_calculation(doc_id).v

        # calkulation for "poprzedni" and "nastepny" button

        doc_id = int(doc_id)

        dec = doc_id - 1

        try:
            dec = Doc.objects.get(pk = dec)
        except Doc.DoesNotExist:
            dec = Doc.objects.order_by('id').first()

        inc = doc_id + 1

        try:
            inc = Doc.objects.get(pk = inc)
        except Doc.DoesNotExist:
            if Doc.objects.order_by('id').last().id == doc_id:
                inc = Doc.objects.order_by('id').last()
            else:
                try:
                    inc = inc + 1
                except inc >= doc_id:
                    pass


'''

class DocCreate(CreateView):
    model = Doc
    fields = ['doctype', 'number', 'date', 'client' ]



    def idreturn(self):
        doc_id = self.id
        return doc_id

class incomeCreate(CreateView):
    model = income
    fields = ['docum', 'product', 'quantity', 'price', 'value']

### Clients section ###


def clients(request):
    return render(request, 'doc/client/clients.html', { 'all_clients': all_clients })

def ClientDetail(request, cli_id):
    try:
        client = Client.objects.get(pk=cli_id)
    except Client.DoesNotExist:
        raise Http404("Client does not exist")

    return render(request, 'doc/client/client_detail.html', { 'client': client })

### Products section

def products(request):
    return render(request, 'doc/products/products.html', { 'all_products': all_products })

def productDetail(request, product_id):
    try:
        product = Product.objects.get(pk=product_id)
    except Product.DoesNotExist:
        raise Http404("Product does not exist")

    return render(request, 'doc/products/product_detail.html', { 'product': product })

doc/templates/doc/products/prod_back.html
<!-- {% extends 'doc/base.html' %}


{% block body %}
<div class = "tab">
    <div id="cli">
        <h1> Lista produktów </h1>

        <ul class="lists">

            {% for product in all_products %}
				<li><a href="{% url 'doc:productDetail' product.id %}"> {{ product }} </a><li>
            {% endfor %}

        </ul>
    </div>
</div>

{% endblock %}

-->

<div class = "container">
    <h2> Lista produktów </h2>
    <table class="table table-hover">
        <thead>
            <tr>
                <th> NAZWA </th>
                <th> ROCZNIK </th>
                <th> KOLOR </th>
                <th> SMAK </th>
            </tr>
        </thead>
        <tbody>
         {% for product in all_products %}
                <tr class='clickable-row' data-href='{% url 'doc:productDetail' product.id %}'>
                    <td> {{ product.name }} </td>
                    <td> {{ product.year }} </td>
                    <td> {{ product.color }} </td>
                    <td> {{ product.dryness }} </td>
                </tr>
         {% endfor %}
        </tbody>
    </table>
</div>

doc/templates/doc/products/product_detail.html
{% extends 'doc/base.html' %}

{% block body %}
<div>
	<h1> Nazwa produktu: {{ product.name }} </h1>
	<br>
	<h2> Kod klienta: {{  }} </h2>
	<br>
	<h1> Ulica: {{  }} </h1>
	<h1> Numer: {{  }} </h1>
	<h1> Miasto: {{  }} </h1>
	<h1> Kod miasta: {{  }} </h1>
	<br>
	<br>
</div>
<br>
<br>
<form action="{% url 'doc:products' %}">
	<button class="btn btn-primary btn-lg" type="submit"> POWRÓT </button>
</form>

{% endblock %}

doc/templates/doc/products/products.html
{% extends 'doc/base.html' %}


{% block body %}

    <div class = "tab">

        <h2 class="list_title"> PRODUKTY </h2>

        <table class="table table-hover">
            <thead>
                <tr>
                    <th> NAZWA </th>
                    <th> ROCZNIK </th>
                    <th> KOLOR </th>
                    <th> SMAK </th>
                </tr>
            </thead>
            <tbody>
                 {% for product in all_products %}
                        <tr class='clickable-row' data-href='{% url 'doc:productDetail' product.id %}'>
                            <td> {{ product.name }} </td>
                            <td> {{ product.year }} </td>
                            <td> {{ product.color }} </td>
                            <td> {{ product.dryness }} </td>
                        </tr>
                 {% endfor %}
            </tbody>
        </table>

    </div>

{% endblock %}